export const hotelTypes = [
  "Boutique Hotel",
  "Luxury Hotel",
  "Resort",
  "Budget Hotel",
  "Hostel",
  "Motel",
  "Extended Stay Hotel",
  "Bed and Breakfast",
  "Business Hotel",
  "Eco-Hotel",
  "All-Inclusive Hotel",
  "Capsule Hotel",
  "Conference Hotel",
  "Historic Hotel",
  "Design Hotel",
  "Ski Resort",
  "Beachfront Hotel",
  "Airport Hotel",
  "Pet-Friendly Hotel",
  "Guesthouse",
  "Timeshare Resort",
];
export const hotelFacilities = [
  "Free Wi-Fi",
  "24-hour front desk",
  "On-site restaurant",
  "Bar/Lounge",
  "Fitness center",
  "Swimming pool",
  "Spa services",
  "Business center",
  "Conference rooms",
  "Room service",
  "Concierge services",
  "Parking (self or valet)",
  "Laundry services",
  "Elevator",
  "Air conditioning",
  "In-room safe",
  "Mini-bar",
  "Coffee/tea maker",
  "Hairdryer",
  "Flat-screen TV",
  "Daily housekeeping",
  "Airport shuttle",
  "Pet-friendly rooms",
  "Non-smoking rooms",
  "Family rooms",
  "Accessible rooms",
  "Luggage storage",
  "Outdoor terrace or garden",
  "Dry cleaning",
  "ATM/cash machine"
];
